version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=Backend;Username=postgres;Password=yourpassword
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  caddy:
    image: caddy:latest
    tty: true
    restart: unless-stopped
    ports:
      - "8081:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./certs:/etc/caddy/certs
    networks:
      - backend-network
    depends_on:
      - app

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  pgdata:

networks:
  backend-network:
    driver: bridge
